openapi: 3.0.0
info:
  title: Expense Tracker API
  version: 1.0.0
  description: API для сервиса отслеживания трат

paths:
  /expenses:
    post:
      summary: Добавить трату
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                category:
                  type: string
                amount:
                  type: number
                date:
                  type: string
                  format: date
      responses:
        '200':
          description: Успешное добавление

  /top-category:
    get:
      summary: Категория с наибольшими тратами за месяц
      parameters:
        - in: query
          name: month
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    type: string
                  total:
                    type: number

  /max-expense:
    get:
      summary: Самая крупная трата в категории и месяце
      parameters:
        - in: query
          name: month
          required: true
          schema:
            type: string
        - in: query
          name: category
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успех
